/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

/**
 * Подсчёт лайков
 */
export type _PostResponseCount = { [key: string]: unknown };
