/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface CategoryRequest {
  /** Название категории */
  name: string;
  /** Цвет категории */
  color: string;
}
