/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */
import type { CategoryResponsePosts } from './categoryResponsePosts';
import type { CategoryResponseProjects } from './categoryResponseProjects';

export interface CategoryResponse {
  /** ID категории */
  id: string;
  /** Название категории */
  name: string;
  /** Цвет категории */
  color: string;
  posts: CategoryResponsePosts;
  projects: CategoryResponseProjects;
}
