/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */
import type { UserResponse } from './userResponse';

export interface CommentResponse {
  /** ID комментария */
  id: string;
  /** Текст комментария */
  text: string;
  /** ID поста */
  postId: string;
  /** Пользователь */
  user: UserResponse;
  /** ID пользователя */
  userId: string;
}
