/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface CommentRequest {
  /** Текст */
  text: string;
  /** ID пользователя */
  userId: string;
}
