/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */
import type { PostCountResponse } from './postCountResponse';
import type { CategoryResponse } from './categoryResponse';
import type { CommentResponse } from './commentResponse';

export interface PostResponse {
  /** ID поста */
  id: string;
  /** Контент поста */
  content: string;
  /** Превью */
  preview: string;
  /**
   * Заголовок поста
   * @minLength 3
   * @maxLength 50
   */
  title: string;
  /** Просмотры */
  views: number;
  /** Подсчёт лайков */
  _count: PostCountResponse;
  /** Категории */
  categories: CategoryResponse[];
  /** Комментарии */
  comments: CommentResponse[];
  /** Дата создания поста */
  createdAt: string;
  /** Дата обновления поста */
  updatedAt: string;
}
