/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface PostRequest {
  /** Контент поста */
  content: string;
  /** Превью */
  preview: string;
  /**
   * Заголовок поста
   * @minLength 3
   * @maxLength 50
   */
  title: string;
  /** Категории */
  categories: string[];
}
