/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface ProjectResponse {
  /** ID поста */
  id: string;
  /** Контент поста */
  content: string;
  /** Превью */
  preview: string;
  /** Превью */
  stack: string[];
  /**
   * Заголовок поста
   * @minLength 3
   * @maxLength 50
   */
  title: string;
  /** Дата создания поста */
  createdAt: string;
}
