/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface RegisterRequest {
  /**
   * Имя пользователя
   * @minLength 3
   */
  username: string;
  /**
   * Пароль пользователя
   * @minLength 8
   */
  password: string;
  /** Почта пользователя */
  email: string;
}
