/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * TiBlog
 * API для сервиса TiBlog
 * OpenAPI spec version: 0.1
 */

export interface UserResponse {
  /** ID пользователя */
  id: string;
  /** Имя пользователя */
  username: string;
  /** Пароль */
  password: string;
  /** Почта */
  email: string;
  /** Роль пользователя */
  role: string;
  /** Дата создания поста */
  createdAt: string;
  /** Дата обновления поста */
  updatedAt: string;
}
